---
version: "3.8"
services:
  code-server:
    build: ./
    container_name: code-server
    ports:
      - "${CODE_PORT:-8080}:8080"
    command: --host 0.0.0.0 --port 8080 --without-connection-token
